import { NextRequest, NextResponse } from 'next/server';

// GET /api/admin/station-installer/generate?portalUrl=...
//
// Returns a double-clickable Windows installer (install.cmd) with the portal
// URL baked in. Operator downloads it, drops it on a USB stick, runs it on a
// fresh station PC — it self-elevates to admin, bypasses PS execution policy,
// downloads bootstrap-station.ps1 from GitHub, and runs the full setup.
//
// No HMAC secret is baked in — the on-prem robot service auto-registers
// unsigned, lands in the portal's quarantine queue, and the operator approves
// it from /admin/station-pcs. That way a leaked USB stick is harmless.
//
// The only thing the portal needs to inject per-download is the portal URL
// itself, because a station may be provisioned for staging, for a Cloudflare
// Tunnel endpoint, or for production.

function escapeCmd(value: string): string {
  // Windows cmd + PowerShell single-quoted string escape. We only allow
  // http(s) URLs, so the set of dangerous chars is narrow, but be careful
  // anyway — the value flows into a PowerShell single-quoted literal.
  return value.replace(/'/g, "''");
}

function buildInstallerScript(portalUrl: string): string {
  const safeUrl = escapeCmd(portalUrl);

  // NOTE: this is a .cmd file. Every line that should be visible as PS source
  // is passed as a single -Command argument. We use `^` for cmd line-continues
  // and `` ` `` for PowerShell line-continues inside the -Command block.
  return [
    '@echo off',
    'REM ============================================================',
    'REM Atelier DSM - Station PC installer',
    `REM Portal: ${portalUrl}`,
    'REM Generated by /api/admin/station-installer/generate',
    'REM',
    'REM What this does:',
    'REM   1. Self-elevates to Administrator (UAC prompt)',
    'REM   2. Downloads bootstrap-station.ps1 from GitHub',
    'REM   3. Runs it with the portal URL pre-filled',
    'REM',
    'REM The PC will register itself with the portal on first boot. Go to',
    `REM ${portalUrl}/admin/station-pcs to approve it.`,
    'REM ============================================================',
    '',
    'setlocal',
    'title Atelier DSM - Station PC Installer',
    '',
    'echo.',
    'echo === Atelier DSM - Station PC Installer ===',
    `echo Portal: ${portalUrl}`,
    'echo.',
    '',
    'REM Self-elevate to Administrator if not already.',
    'net session >nul 2>&1',
    'if %errorLevel% NEQ 0 (',
    '    echo Requesting Administrator privileges...',
    '    powershell -NoProfile -Command "Start-Process -FilePath \'%~f0\' -Verb RunAs"',
    '    exit /b',
    ')',
    '',
    'echo Running with Administrator privileges.',
    'echo.',
    '',
    'REM Run the bootstrap script with the portal URL baked in.',
    'powershell -NoProfile -ExecutionPolicy Bypass -Command ^',
    '  "$ErrorActionPreference = \'Stop\';" ^',
    '  "$url = \'https://raw.githubusercontent.com/GroupeLasernet/lasernet-portal/main/scripts/bootstrap-station.ps1\';" ^',
    '  "$dest = Join-Path $env:TEMP \'bootstrap-station.ps1\';" ^',
    '  "Write-Host \'Downloading bootstrap script...\' -ForegroundColor Cyan;" ^',
    '  "Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing;" ^',
    `  "& $dest -PortalUrl '${safeUrl}'"`,
    '',
    'echo.',
    'echo === Installer finished ===',
    'echo If the script completed without errors, the station PC is now',
    `echo reporting to ${portalUrl}.`,
    'echo.',
    `echo Next step: go to ${portalUrl}/admin/station-pcs`,
    'echo           and approve the new PC (yellow "Pending" badge).',
    'echo.',
    'pause',
    'endlocal',
    '',
  ].join('\r\n');
}

export async function GET(request: NextRequest) {
  try {
    const portalUrlParam = request.nextUrl.searchParams.get('portalUrl');

    // Default to the env-configured portal URL, then request origin as a
    // sensible fallback so a locally-run portal still produces a usable
    // installer out of the box.
    const fallback =
      process.env.NEXT_PUBLIC_PORTAL_URL ||
      process.env.PORTAL_URL ||
      request.nextUrl.origin;

    const raw = (portalUrlParam && portalUrlParam.trim()) || fallback;

    // Very strict URL validation — only http(s) URLs, and strip any trailing
    // slash so the baked-in literal is canonical.
    let url: URL;
    try {
      url = new URL(raw);
    } catch {
      return NextResponse.json({ error: 'Invalid portalUrl' }, { status: 400 });
    }
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      return NextResponse.json({ error: 'portalUrl must be http(s)' }, { status: 400 });
    }
    const canonical = url.origin;

    const script = buildInstallerScript(canonical);

    return new NextResponse(script, {
      status: 200,
      headers: {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': 'attachment; filename="atelier-dsm-station-install.cmd"',
        'Cache-Control': 'no-store',
      },
    });
  } catch (error) {
    console.error('Error generating station installer:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export const dynamic = 'force-dynamic';
